// Build the local place-search index from OpenStreetMap.
//
//   node tools/fetch-poi.js            # CYCU
//   node tools/fetch-poi.js ntu        # another campus in CAMPUSES
//
// Writes src/poi.js. Run it again to refresh; it is a snapshot, not a live
// feed, and that is deliberate:
//
// Nominatim's usage policy prohibits autocomplete-style querying and caps
// callers at one request per second. Searching as the user types would breach
// it, and the penalty is an IP block — which would land during a demo. A 26 KB
// file answers instantly, needs no network, and cannot be rate limited.
//
// Coverage is good enough to rely on: 361 named food places within 1.2 km of
// CYCU, every one of them carrying a name tag.

import { writeFileSync } from 'node:fs'

const CAMPUSES = {
  cycu: { lat: 24.9572, lng: 121.2422 },
  ntu: { lat: 25.0174, lng: 121.5395 }
}

const campus = process.argv[2] || 'cycu'
const here = CAMPUSES[campus]
if (!here) {
  console.error(`unknown campus "${campus}" — known: ${Object.keys(CAMPUSES).join(', ')}`)
  process.exit(1)
}

const RADIUS = 1200

// Mapped onto the app's own categories, so a search result can drop a pin of
// the right type instead of everything becoming "food".
const KINDS = {
  food: 'restaurant|fast_food|food_court|cafe|ice_cream|bar|pub',
  shop: 'convenience|supermarket|marketplace',
  laundry: 'laundry',
  print: 'copyshop'
}

const AMENITY_TO_TYPE = new Map()
for (const [type, list] of Object.entries(KINDS)) {
  for (const a of list.split('|')) AMENITY_TO_TYPE.set(a, type)
}

const amenities = Object.values(KINDS).join('|')

// shop=* covers convenience stores and laundries, which are not amenities.
const query = `[out:json][timeout:90];
(
  node[amenity~"${amenities}"](around:${RADIUS},${here.lat},${here.lng});
  way[amenity~"${amenities}"](around:${RADIUS},${here.lat},${here.lng});
  node[shop~"convenience|supermarket|laundry|copyshop|bakery"](around:${RADIUS},${here.lat},${here.lng});
  way[shop~"convenience|supermarket|laundry|copyshop|bakery"](around:${RADIUS},${here.lat},${here.lng});
);
out center tags;`

const SHOP_TO_TYPE = {
  convenience: 'shop', supermarket: 'shop', bakery: 'food',
  laundry: 'laundry', copyshop: 'print'
}

console.log(`fetching OSM places within ${RADIUS}m of ${campus}…`)

const res = await fetch('https://overpass-api.de/api/interpreter', {
  method: 'POST',
  headers: { 'User-Agent': 'FreshmanMap/1.0 (student project)' },
  body: new URLSearchParams({ data: query })
})

if (!res.ok) {
  console.error(`Overpass returned ${res.status}. It rate limits; wait a minute and retry.`)
  process.exit(1)
}

const { elements } = await res.json()

const seen = new Set()
const rows = []

for (const el of elements) {
  const t = el.tags || {}
  const name = t.name || t['name:zh'] || t['name:en']
  if (!name) continue

  const lat = el.lat ?? el.center?.lat
  const lng = el.lon ?? el.center?.lon
  if (!lat || !lng) continue

  // An OSM place mapped as both a node and a building way appears twice.
  const key = `${name}@${lat.toFixed(4)},${lng.toFixed(4)}`
  if (seen.has(key)) continue
  seen.add(key)

  rows.push({
    n: name,
    e: t['name:en'] && t['name:en'] !== name ? t['name:en'] : undefined,
    t: AMENITY_TO_TYPE.get(t.amenity) || SHOP_TO_TYPE[t.shop] || 'food',
    lat: Number(lat.toFixed(6)),
    lng: Number(lng.toFixed(6))
  })
}

rows.sort((a, b) => a.n.localeCompare(b.n, 'zh-Hant'))

const file = `// GENERATED by tools/fetch-poi.js — do not edit by hand.
// ${rows.length} OpenStreetMap places within ${RADIUS}m of ${campus}.
// Refresh with:  node tools/fetch-poi.js ${campus}
//
// Bundled rather than queried live: Nominatim forbids autocomplete-style
// requests, and a file cannot be rate limited in the middle of a demo.

export const POI = ${JSON.stringify(rows, null, 0)}
`

writeFileSync('src/poi.js', file)

const byType = rows.reduce((acc, r) => ({ ...acc, [r.t]: (acc[r.t] || 0) + 1 }), {})
console.log(`wrote src/poi.js — ${rows.length} places, ${(file.length / 1024).toFixed(1)} KB`)
console.log(' ', Object.entries(byType).map(([k, v]) => `${k} ${v}`).join('  '))
